"""Generate the MSFMamba few-shot config grid for all project datasets."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONFIGS = ROOT / "configs"
SHOTS = (5, 10, 20, 50, 100, 150, 200)
DATASETS = {
    "yrd": {"sar_channels": 4, "colors": [[62, 69, 191], [224, 190, 82], [158, 219, 74], [77, 214, 83], [63, 197, 153], [174, 205, 45], [181, 77, 218], [255, 250, 0]]},
    "yrd2509new": {"sar_channels": 4},
}
DEFAULT_COLORS = [[31, 120, 180], [78, 205, 196], [51, 160, 44], [246, 204, 92], [8, 81, 156], [227, 26, 28], [106, 61, 154], [255, 127, 0], [0, 109, 44], [166, 206, 227], [178, 223, 138], [251, 154, 153], [80, 80, 80]]


def _yaml_config(dataset: str, sar_channels: int, shot: int, colors: list[list[int]]) -> str:
    color_lines = "\n".join(f"    - [{red}, {green}, {blue}]" for red, green, blue in colors)
    return f"""# Generated by scripts/generate_msfmamba_configs.py.
model: msfmamba
dataset: {dataset}
dataset_config: configs/datasets/{dataset}.yaml
output_root: runs_fewshot/fs{shot}
device: cuda:0
patch_size: 11
ms_channels: 10
sar_channels: {sar_channels}
num_layers: 1
d_state: 16
expand: 0.75
split:
  method: fixed_train_counts
  train_count_per_class: {shot}
use_validation: false
select_best_by: last
test_interval: 0
batch_size: 128
test_batch_size: 1024
epochs: 200
num_runs: 5
seeds: [202201, 202202, 202203, 202204, 202205]
data_aug: true
learning_rate: 0.0001
weight_decay: 0.0
eval:
  enabled: true
  run_index: best
  batch_size: 1024
  save_labeled_maps: true
infer:
  batch_size: 512
  save_full_map: true
palette:
  background: [0, 0, 0]
  colors:
{color_lines}
"""


def main() -> None:
    for dataset, details in DATASETS.items():
        for shot in SHOTS:
            target = CONFIGS / f"msfmamba_{dataset}_fs{shot}.yaml"
            target.write_text(
                _yaml_config(dataset, details["sar_channels"], shot, details.get("colors", DEFAULT_COLORS)),
                encoding="utf-8",
            )
            print(target.relative_to(ROOT))


if __name__ == "__main__":
    main()
